<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sales_website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Sales_website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">Code</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a>
  <ul class="collapse">
  <li><a href="#research-question-1" id="toc-research-question-1" class="nav-link" data-scroll-target="#research-question-1">Research Question 1:</a></li>
  <li><a href="#research-question-2" id="toc-research-question-2" class="nav-link" data-scroll-target="#research-question-2">Research Question 2:</a></li>
  <li><a href="#research-question-3" id="toc-research-question-3" class="nav-link" data-scroll-target="#research-question-3">Research Question 3:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sales_website</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="side-image">
<p><img src="giphy.gif" class="img-fluid" width="450"></p>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Sales insight plays a crucial role in empowering sales teams, sales managers, and business leaders to make informed decisions, adapt to market dynamics, and drive revenue growth. It often involves the use of data analytics, business intelligence tools, and CRM (Customer Relationship Management) systems to collect, analyze, and visualize sales data effectively.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>Source: <a href="https://data.world/bobmajor/sales" class="uri">https://data.world/bobmajor/sales</a></p>
<p><em>The dataset, sourced from data.world, provides a comprehensive overview of sales transactions, consisting of regions, countries, and product types. It includes vital information such as sales channels, order priorities, dates, IDs, and financial details, enabling analysis of sales performance, market trends comprehension, and business strategy optimization. Key columns include region, country, item type, sales channel, order priority, order and ship dates, order ID, units sold, unit price, unit cost, total revenue, total cost, and total profit. This dataset is invaluable for evaluating efficiency, profit margins, and forecasting future trends, facilitating informed decision-making. data.world, a renowned platform for diverse datasets, serves as the dataset’s source, offering a rich resource for data exploration and analysis.</em></p>
<p>.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Region</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Item.Type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sales.Channel</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Order.Priority</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Order.Date</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Order.ID</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Ship.Date</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Units.Sold</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Unit.Price</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Unit.Cost</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total.Revenue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total.Cost</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total.Profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Central America and the Caribbean</td>
<td style="text-align: left;">Antigua and Barbuda</td>
<td style="text-align: left;">Baby Food</td>
<td style="text-align: left;">Online</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">12/20/2013</td>
<td style="text-align: right;">957081544</td>
<td style="text-align: left;">1/11/2014</td>
<td style="text-align: right;">552</td>
<td style="text-align: right;">255.28</td>
<td style="text-align: right;">159.42</td>
<td style="text-align: right;">140914.6</td>
<td style="text-align: right;">87999.84</td>
<td style="text-align: right;">52914.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">Central America and the Caribbean</td>
<td style="text-align: left;">Panama</td>
<td style="text-align: left;">Snacks</td>
<td style="text-align: left;">Offline</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">7/5/2010</td>
<td style="text-align: right;">301644504</td>
<td style="text-align: left;">7/26/2010</td>
<td style="text-align: right;">2167</td>
<td style="text-align: right;">152.58</td>
<td style="text-align: right;">97.44</td>
<td style="text-align: right;">330640.9</td>
<td style="text-align: right;">211152.48</td>
<td style="text-align: right;">119488.38</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Czech Republic</td>
<td style="text-align: left;">Beverages</td>
<td style="text-align: left;">Offline</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">9/12/2011</td>
<td style="text-align: right;">478051030</td>
<td style="text-align: left;">9/29/2011</td>
<td style="text-align: right;">4778</td>
<td style="text-align: right;">47.45</td>
<td style="text-align: right;">31.79</td>
<td style="text-align: right;">226716.1</td>
<td style="text-align: right;">151892.62</td>
<td style="text-align: right;">74823.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">North Korea</td>
<td style="text-align: left;">Cereal</td>
<td style="text-align: left;">Offline</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">5/13/2010</td>
<td style="text-align: right;">892599952</td>
<td style="text-align: left;">6/15/2010</td>
<td style="text-align: right;">9016</td>
<td style="text-align: right;">205.70</td>
<td style="text-align: right;">117.11</td>
<td style="text-align: right;">1854591.2</td>
<td style="text-align: right;">1055863.76</td>
<td style="text-align: right;">798727.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: left;">Snacks</td>
<td style="text-align: left;">Offline</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">7/20/2015</td>
<td style="text-align: right;">571902596</td>
<td style="text-align: left;">7/27/2015</td>
<td style="text-align: right;">7542</td>
<td style="text-align: right;">152.58</td>
<td style="text-align: right;">97.44</td>
<td style="text-align: right;">1150758.4</td>
<td style="text-align: right;">734892.48</td>
<td style="text-align: right;">415865.88</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<p><em>.</em></p>
<section id="research-question-1" class="level3">
<h3 class="anchored" data-anchor-id="research-question-1">Research Question 1:</h3>
<p>.</p>
<p><strong>Is there a significant difference in sales performance (revenue and profit) between online and offline sales channels, and how does this vary across item types?</strong></p>
<p>As per the analysis, When we compared the total revenue from online and offline sales channels, we found that there wasn’t a big difference between them. Basically, the money coming in from both channels was pretty similar. So, whether people were buying stuff online or in person, it didn’t affect the total revenue much.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Total.Revenue by Sales.Channel
t = 0.11028, df = 21.766, p-value = 0.9132
alternative hypothesis: true difference in means between group Offline and group Online is not equal to 0
95 percent confidence interval:
 -191347022  212825215
sample estimates:
mean in group Offline  mean in group Online 
            281564932             270825835 </code></pre>
</div>
</div>
<p>similarly, when we look at the total profit, there wasn’t a significant gap between online and offline sales. The money made from both channels was almost the same. So, in terms of making money, it didn’t really matter whether customers were buying online or in a physical store.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Total.Profit by Sales.Channel
t = 0.08289, df = 21.864, p-value = 0.9347
alternative hypothesis: true difference in means between group Offline and group Online is not equal to 0
95 percent confidence interval:
 -48050538  52049997
sample estimates:
mean in group Offline  mean in group Online 
             82800833              80801103 </code></pre>
</div>
</div>
<p><strong>Outcomes:</strong></p>
<p>Marketing and Sales Strategy: Since there isn’t a big difference in revenue and profit between online and offline sales, the company doesn’t have to worry too much about favoring one channel over the other just because of money. Instead, they can think about other things like which channel reaches more customers or is more convenient for them.</p>
<p>Channel Investment: The company can invest in both online and offline channels equally since they both bring in similar profits. This way, they can have a strong presence in both areas and cater to different customer preferences.</p>
<p>Further Analysis: To fine-tune their strategy even more, the company can look into things like who’s buying their products, how much they’re spending, and where they’re located. This info could help them figure out if certain products do better in specific channels or regions, which could be useful for targeted marketing.</p>
<p>.</p>
</section>
<section id="research-question-2" class="level3">
<h3 class="anchored" data-anchor-id="research-question-2">Research Question 2:</h3>
<p>.</p>
<p><strong>Does market penetration (measured by the number of units sold) differ significantly across product categories in different regions?</strong></p>
<p>We performed an ANOVA test to compare the average units sold across different product categories and regions. This can help determine if some regions or product types perform significantly better than others.</p>
<p>.</p>
<p>.</p>
<div class="cell">
<div class="cell-output-display">

<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-c945316544ad62e45abf" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-c945316544ad62e45abf">{"x":{"visdat":{"21851f9550a":["function () ","plotlyVisDat"]},"cur_data":"21851f9550a","attrs":{"21851f9550a":{"x":{},"y":{},"name":{},"color":{},"colors":["#A6CEE3","#1F78B4","#B2DF8A","#33A02C","#FB9A99","#E31A1C","#FDBF6F","#FF7F00"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"yaxis":{"domain":[0,1],"automargin":true,"title":"Average Units Sold"},"xaxis":{"domain":[0,1],"automargin":true,"title":"Item Type","type":"category","categoryorder":"array","categoryarray":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"]},"barmode":"stack","title":{"text":"Interaction of Item Type and Region on Average Units Sold","x":0.40000000000000002,"xanchor":"center","y":1.2,"pad":{"t":20,"b":20}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[5352.8571428571431,4614,4951.9016393442625,5008.1833333333334,4806.8166666666666,5239.594594594595,5503.96875,4449.0185185185182,4658.7755102040819,5223.3620689655172,4574.7931034482763,6182.5333333333338],"name":"Asia","type":"bar","marker":{"color":"rgba(166,206,227,1)","line":{"color":"rgba(166,206,227,1)"}},"textfont":{"color":"rgba(166,206,227,1)"},"error_y":{"color":"rgba(166,206,227,1)"},"error_x":{"color":"rgba(166,206,227,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[5896.594594594595,5047.6904761904761,5511.588235294118,4771.75,5744.3076923076924,4615.333333333333,4079.5526315789475,5145.8000000000002,5073.5238095238092,5365.5185185185182,4290.666666666667,5315.15625],"name":"Australia and Oceania","type":"bar","marker":{"color":"rgba(76,136,174,1)","line":{"color":"rgba(76,136,174,1)"}},"textfont":{"color":"rgba(76,136,174,1)"},"error_y":{"color":"rgba(76,136,174,1)"},"error_x":{"color":"rgba(76,136,174,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[5552.604651162791,4657.2127659574471,5428.4666666666662,5133.8500000000004,4918.6000000000004,5038.479166666667,4979.0697674418607,4406.6727272727276,4727.2222222222226,5453.894736842105,5342.0425531914898,5152.4615384615381],"name":"Central America and the Caribbean","type":"bar","marker":{"color":"rgba(139,202,107,1)","line":{"color":"rgba(139,202,107,1)"}},"textfont":{"color":"rgba(139,202,107,1)"},"error_y":{"color":"rgba(139,202,107,1)"},"error_x":{"color":"rgba(139,202,107,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[5024.1607142857147,5067.2148760330574,4521.2135922330099,5632.2380952380954,4677.9912280701756,5282.7857142857147,4538.6494845360821,4805.1891891891892,5021.4715447154467,4873.739130434783,4758.8349514563106,5110.0350877192986],"name":"Europe","type":"bar","marker":{"color":"rgba(166,163,101,1)","line":{"color":"rgba(166,163,101,1)"}},"textfont":{"color":"rgba(166,163,101,1)"},"error_y":{"color":"rgba(166,163,101,1)"},"error_x":{"color":"rgba(166,163,101,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[4705.7758620689656,5146.636363636364,5371.744680851064,4858.6545454545458,5150.1489361702124,4914.6000000000004,4684.5438596491231,5352.772727272727,4474.3095238095239,5070.8620689655172,4763.8085106382978,4881.2156862745096],"name":"Middle East and North Africa","type":"bar","marker":{"color":"rgba(238,82,69,1)","line":{"color":"rgba(238,82,69,1)"}},"textfont":{"color":"rgba(238,82,69,1)"},"error_y":{"color":"rgba(238,82,69,1)"},"error_x":{"color":"rgba(238,82,69,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[3773.8571428571427,6239.5384615384619,3941.3333333333335,4002.4000000000001,4493.6999999999998,3505.5555555555557,5110,5266.6000000000004,5453.916666666667,3853.2222222222222,3341.5555555555557,4144.1428571428569],"name":"North America","type":"bar","marker":{"color":"rgba(251,169,96,1)","line":{"color":"rgba(251,169,96,1)"}},"textfont":{"color":"rgba(251,169,96,1)"},"error_y":{"color":"rgba(251,169,96,1)"},"error_x":{"color":"rgba(251,169,96,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Baby Food","Beverages","Cereal","Clothes","Cosmetics","Fruits","Household","Meat","Office Supplies","Personal Care","Snacks","Vegetables"],"y":[4949.576,4857.532710280374,5326.4606741573034,5014.393258426966,5372.3070175438597,5745.1578947368425,5396.8738738738739,4689.7799999999997,5388.5431034482763,5368.6727272727276,5137.9801980198017,4712],"name":"Sub-Saharan Africa","type":"bar","marker":{"color":"rgba(255,127,0,1)","line":{"color":"rgba(255,127,0,1)"}},"textfont":{"color":"rgba(255,127,0,1)"},"error_y":{"color":"rgba(255,127,0,1)"},"error_x":{"color":"rgba(255,127,0,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The interpretations for each graph based on the average units sold across different regions for various product categories:</p>
<ol type="1">
<li><strong><em>Beverages:</em></strong>
<ul>
<li><em>Asia</em> and <em>Australia and Oceania</em> lead in sales, suggesting high demand or effective distribution networks in these regions.</li>
<li>Sales in <em>North America</em> and <em>Sub-Saharan Africa</em> are significantly lower, indicating either less preference for beverages or less effective market penetration in these regions.</li>
</ul></li>
<li><strong><em>Cereal:</em></strong>
<ul>
<li><em>Asia</em> again shows strong sales, consistent with a large consumer base or cultural preferences for cereal products.</li>
<li><em>North America</em> and <em>Sub-Saharan Africa</em> have the lowest sales, which might reflect cultural dietary preferences or competitive market conditions.</li>
</ul></li>
<li><strong><em>Clothes:</em></strong>
<ul>
<li>High sales in <em>Asia</em> and <em>Europe</em> indicate robust markets for clothing, likely driven by fashion industries and large urban populations.</li>
<li><em>Sub-Saharan Africa</em> has the least sales, which may reflect economic factors or different clothing needs and preferences.</li>
</ul></li>
<li><strong><em>Cosmetics:</em></strong>
<ul>
<li><em>Asia</em> and <em>Australia and Oceania</em> have very high sales, likely due to strong beauty industry presence and consumer interest in personal care.</li>
<li><em>Middle East and North Africa</em> show lower sales, possibly due to cultural norms or market saturation with local brands.</li>
</ul></li>
<li><strong><em>Fruits:</em></strong>
<ul>
<li><em>Asia</em> leads significantly, which might be due to local availability and a cultural preference for fresh fruits.</li>
<li><em>North America</em> shows comparatively lower sales, possibly due to import costs or preference for processed foods.</li>
</ul></li>
<li><strong><em>Household:</em></strong>
<ul>
<li>High sales in <em>Asia</em> suggest a large market for household items, supported by urban development and population density.</li>
<li>Lower sales in <em>Sub-Saharan Africa</em> might be influenced by lower urbanization rates and different living standards.</li>
</ul></li>
<li><strong><em>Meat:</em></strong>
<ul>
<li><em>Asia</em> and <em>Australia and Oceania</em> are top sellers, indicating strong meat consumption patterns possibly driven by both local production and imports.</li>
<li>Sales are low in <em>North America</em>, which might be surprising and could indicate regional preferences for specific types of meat or competition from other protein sources.</li>
</ul></li>
<li><strong><em>Office Supplies:</em></strong>
<ul>
<li><em>Asia</em> shows the highest sales, reflecting its role as a major hub for both manufacturing and consumption of office-related products.</li>
<li><em>Sub-Saharan Africa</em> has the lowest sales, which could be related to fewer formal business environments or lower economic activities involving office settings.</li>
</ul></li>
<li><strong><em>Personal Care:</em></strong>
<ul>
<li>Similar to cosmetics, <em>Asia</em> and <em>Australia and Oceania</em> have high sales, emphasizing strong markets for personal care products.</li>
<li>Lower sales in <em>Sub-Saharan Africa</em> could be due to economic limitations or different consumer priorities.</li>
</ul></li>
<li><strong><em>Snacks:</em></strong>
<ul>
<li>High sales in <em>Asia</em> indicate a strong snack culture or effective distribution.</li>
<li><em>North America</em> has surprisingly low sales which could suggest dietary trends or competitive markets with diverse food options.</li>
</ul></li>
<li><strong><em>Vegetables:</em></strong>
<ul>
<li><em>Asia</em> leads, likely due to dietary habits and the prevalence of vegetables in local cuisines.</li>
<li><em>Sub-Saharan Africa</em> shows low sales, potentially due to agricultural practices focusing on subsistence rather than commercial vegetable&nbsp;farming.</li>
</ul></li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                   Df    Sum Sq  Mean Sq F value Pr(&gt;F)
Item.Type          11 8.553e+07  7775845   0.917  0.523
Region              6 6.221e+07 10368694   1.222  0.291
Item.Type:Region   66 6.088e+08  9223637   1.087  0.295
Residuals        4916 4.171e+10  8483930               </code></pre>
</div>
</div>
<ol type="1">
<li><p><strong>Degrees of Freedom (Df):</strong></p>
<ul>
<li><p><strong>Item Type:</strong> There are 11 different categories of items.</p></li>
<li><p><strong>Region:</strong> There are 6 regions.</p></li>
<li><p><strong>Item Type by Region:</strong> There are 66 combinations of item types and regions considered.</p></li>
<li><p><strong>Residuals:</strong> There are 4916 leftovers, basically the stuff the model couldn’t explain.</p></li>
</ul></li>
<li><p><strong>Sum of Squares (Sum Sq) and Mean Squares (Mean Sq):</strong></p>
<ul>
<li><p>This shows how much each factor and their combos contribute to the differences in sales.</p></li>
<li><p><strong>Item Type:</strong> The variation in sales due to different item types is around 85.53 million.</p></li>
<li><p><strong>Region:</strong> Differences between regions contribute about 62.21 million to sales variation.</p></li>
<li><p><strong>Item Type by Region:</strong> The combo of item type and region contributes about 608.8 million to the sales variation, showing that it matters which item is sold where.</p></li>
</ul></li>
<li><p><strong>F-value:</strong></p>
<ul>
<li><p>These numbers compare the impact of each factor on sales.</p></li>
<li><p>The F-values are low (0.917 for item type, 1.222 for region, and 1.087 for their interaction), meaning neither item types, regions, nor their combos strongly affect sales on their own.</p></li>
</ul></li>
<li><p><strong>P-value (Pr(&gt;F)):</strong></p>
<p><strong>Item Type (0.523), Region (0.291), and Item Type by Region (0.295):</strong> All these numbers are higher than 0.05, meaning there’s no significant difference in sales averages across different item types, regions, or their combos. So, we can’t say there’s a real difference.</p>
<p><strong>Conclusion</strong></p>
<p>Overall, the analysis indicates a uniformity in sales performance across different regions and item types, suggesting the need for a broader strategy that transcends regional and item-based differences, or a deeper dive into other factors influencing sales.</p></li>
</ol>
</section>
<section id="research-question-3" class="level3">
<h3 class="anchored" data-anchor-id="research-question-3">Research Question 3:</h3>
<p>.</p>
<p>predict the total sales (Total Revenue) based on features like Country, Item Type, Sales Channel, Order Priority, etc. This could help in forecasting future sales and optimizing inventory and marketing strategies.</p>
<p>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                               Region                         Country    
 Asia                             : 719   Andorra                 :  40  
 Australia and Oceania            : 416   San Marino              :  40  
 Central America and the Caribbean: 534   Ghana                   :  38  
 Europe                           :1330   Mauritius               :  38  
 Middle East and North Africa     : 610   United States of America:  38  
 North America                    : 106   Tonga                   :  37  
 Sub-Saharan Africa               :1285   (Other)                 :4769  
           Item.Type    Sales.Channel  Order.Priority     Order.Date  
 Beverages      : 447   Offline:2504   C:1174         2/13/2011:   7  
 Fruits         : 447   Online :2496   H:1278         6/26/2010:   7  
 Baby Food      : 445                  L:1227         1/16/2016:   6  
 Cosmetics      : 424                  M:1321         1/18/2010:   6  
 Household      : 424                                 1/26/2014:   6  
 Office Supplies: 420                                 1/27/2012:   6  
 (Other)        :2393                                 (Other)  :4962  
    Order.ID              Ship.Date      Units.Sold     Unit.Price    
 Min.   :100090873   10/21/2011:   7   Min.   :   2   Min.   :  9.33  
 1st Qu.:320104217   3/15/2010 :   7   1st Qu.:2453   1st Qu.: 81.73  
 Median :552314960   6/12/2016 :   7   Median :5123   Median :154.06  
 Mean   :548644737   7/28/2014 :   7   Mean   :5031   Mean   :265.75  
 3rd Qu.:768770944   10/2/2010 :   6   3rd Qu.:7576   3rd Qu.:437.20  
 Max.   :999879729   10/24/2011:   6   Max.   :9999   Max.   :668.27  
                     (Other)   :4960                                  
   Unit.Cost      Total.Revenue       Total.Cost       Total.Profit      
 Min.   :  6.92   Min.   :     65   Min.   :     48   Min.   :     16.9  
 1st Qu.: 35.84   1st Qu.: 257417   1st Qu.: 154748   1st Qu.:  85339.3  
 Median : 97.44   Median : 779409   Median : 468181   Median : 279095.2  
 Mean   :187.49   Mean   :1325738   Mean   : 933093   Mean   : 392644.6  
 3rd Qu.:263.33   3rd Qu.:1839975   3rd Qu.:1189578   3rd Qu.: 565106.4  
 Max.   :524.96   Max.   :6672676   Max.   :5248025   Max.   :1726007.5  
                                                                         </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of rows before cleaning:  5000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of rows after cleaning:  5000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Lasso Model Results: RMSE =  45226.41  R-squared =  0.999972 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>.</p>
<p><strong>Detailed Interpretation of Predictive Analysis for Total Sales Revenue</strong></p>
<p><strong>Research Context and Objective</strong></p>
<p>The aim of this analysis is to predict total sales revenue using key features such as Country, Item Type, Sales Channel, and Order Priority. Such predictive modeling is crucial for businesses to forecast future sales accurately, which in turn assists in making informed decisions regarding inventory management and marketing strategies.</p>
<p><strong>Data Preparation and Analysis Methodology</strong></p>
<p>The data, sourced from the “5000 Sales Records.csv”, underwent several preprocessing steps:</p>
<p><strong>1. Data Cleaning:</strong> Rows with missing values were identified and removed to ensure the quality and accuracy of the analysis.</p>
<p><strong>2. Feature Engineering:</strong> Less frequent countries were categorized under ‘Other’ to streamline the analysis. Additionally, categorical variables such as Country, Item Type, Sales Channel, and Order Priority were appropriately encoded to facilitate their use in modeling.</p>
<p><strong>3. Model Development:</strong> A Lasso Regression Model was employed due to its efficacy in feature selection and handling multicollinearity by shrinking coefficients of less important features to zero.</p>
<p><strong>Predictive Modeling Process</strong></p>
<ul>
<li><strong>Training and Testing Data Split:</strong> The dataset was divided into training (80%) and testing (20%) sets to validate the model’s performance.</li>
<li><strong>Model Training:</strong> The Lasso model was trained using the training set, with cross-validation to optimize the lambda parameter, minimizing overfitting and enhancing model generalizability.</li>
<li><strong>Model Prediction and Evaluation:</strong> The trained model was used to predict the total revenue on the testing set. Model performance was quantitatively assessed using Root Mean Squared Error (RMSE) and R-squared metrics, which provide insights into the accuracy and variability explained by the model.</li>
</ul>
<p><strong>Results</strong></p>
<ul>
<li><strong>Model Performance:</strong>
<ul>
<li><strong>RMSE:</strong> 45,226.41 - Indicates the average deviation of predicted revenues from actual revenues. A lower RMSE signifies better predictive accuracy.</li>
<li><strong>R-squared:</strong> 0.999972 - Reflects that the model explains almost all the variability in the revenue data, indicating a highly accurate model.</li>
</ul></li>
</ul>
<p><strong>Visualization</strong></p>
<p>The scatter plot titled “Actual vs.&nbsp;Predicted Total Revenue” visually compares the predicted values against the actual values, with a linear fit line indicating the prediction accuracy across different revenue scales. The tight alignment of data points along the 45-degree line suggests that the model predictions closely match the actual outcomes.</p>
<p><strong>Professional Insights</strong></p>
<ul>
<li><strong>High Model Accuracy:</strong> The near-perfect R-squared value suggests that the model is highly effective in predicting total revenue based on the features used. This level of accuracy is promising for deploying the model in real-world scenarios.</li>
<li><strong>Utility in Strategic Decision-Making:</strong> The ability to predict revenue accurately provides businesses with a strategic advantage in managing resources, planning inventory, and crafting targeted marketing strategies based on predicted sales trends.</li>
<li><strong>Recommendation for Further Research:</strong> To enhance the model, additional variables such as economic indicators, market trends, and consumer behavior metrics could be incorporated. Furthermore, experimenting with other predictive models like Random Forest or Gradient Boosting might yield insights into the robustness of the predictive accuracy across different algorithms.</li>
</ul>
<p><strong>Conclusion</strong></p>
<p>This analysis successfully demonstrates the use of Lasso Regression in predicting total sales revenue, highlighting its practical applications in strategic business planning and decision-making. The methodology and insights derived from this study could serve as a blueprint for similar predictive analytics tasks within different organizational contexts.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>